import Head from 'next/head';
import Header from '@/components/layouts/Header';
import Offers from '@/modules/hero_section/Offers';
import Category from '@/modules/category/Category';
import Products from '@/modules/products/Products';
import Cta from '@/modules/cta/Cta';

// images
import ctaImage from '@/images/products/cta.jpg';
import Footer from '@/components/layouts/Footer';

const productList = [
  {
    id: 1,
    title: 'T-shirt',
    image: '/images/products/product1.png',
    offer: 15,
    price: 100,
    href: '/',
  },
  {
    id: 2,
    title: "Women's jacket",
    image: '/images/products/product2.png',
    offer: 15,
    price: 12,
    href: '/',
  },
  {
    id: 3,
    title: 'Side bag',
    image: '/images/products/product3.png',
    offer: 15,
    price: 12,
    href: '/',
  },
  {
    id: 4,
    title: "Men's jacket",
    image: '/images/products/product4.png',
    offer: 15,
    price: 12,
    href: '/',
  },
  {
    id: 5,
    title: 'Hat',
    image: '/images/products/product5.png',
    offer: 15,
    price: 12,
    href: '/',
  },
  {
    id: 6,
    title: 'Shoe',
    image: '/images/products/product6.png',
    offer: 15,
    price: 12,
    href: '/',
  },
  {
    id: 7,
    title: 'wrist',
    image: '/images/products/product7.png',
    offer: 15,
    price: 12,
    href: '/',
  },
];

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Offers />
      <Category />
      <Products list={productList} title="New arrival" />
      <Products list={productList} title="Trending Collections" />
      <Cta image={ctaImage} />
      <Footer />
    </div>
  );
}
